### ISSUE TITLE
`sync.RWMutex` is mentioned without introduction

### ISSUE THREAD

**Issue by blaise-io** [karlseguin/the-little-go-book#21]
[You mention `sync.RWMutex` as a term here.](
https://github.com/karlseguin/the-little-go-book/blame/6606a6c0732ae9e8a7cb14e74a3b54ffec5d9826/en/go.md#L1648) But up until that paragraph, you have only explained how  `sync.Mutex` works, without mentioning or explaining `sync.RWMutex`.

I had to look it up, and [this](http://www.alexedwards.net/blog/understanding-mutexes) explained it in a way I understand:
> […]  It would be OK for us to have multiple reads of Balance happening at the same time, so long as nothing is being written.
>
> We can achieve this using RWMutex, a reader/writer mutual exclusion lock which allows any number of readers to hold the lock or one writer. Depending on the nature of your application and ratio of reads to writes, this may be more efficient than using a full mutex.

Maybe you can adjust this chapter to quickly introduce `sync.RWMutex`?

**Comment by karlseguin** [comment]
What do you think of: https://github.com/karlseguin/the-little-go-book/commit/86403b5f832b938f018ec80f3f56742dac6df028 ?

**Comment by blaise-io** [comment]
Perfect, thanks!
