### ISSUE TITLE
Introduction of New is not clear

### ISSUE THREAD

**Issue by HParker** [karlseguin/the-little-go-book#27]
I was confused reading the section on [slices](https://github.com/karlseguin/the-little-go-book/blob/master/en/go.md#slices) saying,
> We use make instead of new because there's more to creating a slice than just allocating the memory (which is what new does).

As someone who is new to Go, I have never used `new` or `make`. I don't know what it means for new to just allocate the memory. Instead I referred to [effective go](https://golang.org/doc/effective_go.html#allocation_new) to better understand the comparison.

How would you feel about a short introduction to `new` maybe in the [constructors](https://github.com/karlseguin/the-little-go-book/blob/master/en/go.md#constructors) section?

or maybe a link to read further?

**Comment by karlseguin** [comment]
Mind reviewing the new section in the branch:
https://github.com/karlseguin/the-little-go-book/commit/d98987035578ba1e43e441f04d4b491bc18117a8#diff-43b5a86d72117276f09b0b9b9573a4a9R549

**Comment by HParker** [comment]
:+1: awesome. seeing it is the same as `&Saiyan{}` is perfect.
