### ISSUE TITLE
Link to the Spanish Translation

### ISSUE THREAD

**Issue by raulexposito** [karlseguin/the-little-go-book#28]
Hi Karl,

I'm absolutely sure you don't remember me, but I translated your "The Little Redis Book" to Spanish a few years ago.

In this occasion I've translated "The Little Go Book": 
https://github.com/raulexposito/the-little-go-book

Here you are a direct link to the PDF:
https://github.com/raulexposito/the-little-go-book/raw/master/es/go.pdf

I was finding great resources to learn Go and, by coincidence, I found your book. In my opinion is a masterpiece and, for that reason, I've translated it :-)

Thanks for your time and the effort you've made writing it!

Regards!

**Comment by karlseguin** [comment]
Thanks! I added a link to it in the Readme.
