### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by tombusby** [karlseguin/the-little-go-book#37]
Hi Karl,

Feel free to close this issue once you've read it. I finished working through this book last night and I really thoroughly enjoyed it. I kept a small list of things I felt were unclear or could be improved. I'm going to submit each of these as a PR over the next day or two.

I just wanted to leave this message so that you knew it wasn't a criticism of the book as a whole, which I think is fantastic. Whether you accept all or none of my proposals, I'm just glad to be a part of helping this fantastic book mature.

Tom Busby

**Comment by karlseguin** [comment]
thanks :)
