### ISSUE TITLE
Executable command 

### ISSUE THREAD

**Issue by matiux** [karlseguin/the-little-go-book#44]
I'm reading the "Packages" chapter but there is a point that I don't understand. I have created "shopping" application with this folders structure:
```
- src
   - bitbucket.org
      - matiux
         - shopping
            - db
               db.go
            - main
               main.go
            - models
               item.go
            pricecheck.go      
```
First of all, to make the application running, unlike from your example, i have imported `bitbucket.org/matiux/shopping` in main/main.go because i have created the project in `src/bitbucket.org/matiux` folder (you have used only `src` folder).

When I execute `go run main/main.go`, the program works but the think that I don't understand is why in `$GOPATH/bin` there isn't the executable command? Maybe because the main.go file is in main folder?

All the other examples that I wrote, have main.go in  `$GOPATH/src/bitbucket.org/matiux/program_name` so, after `go install` command (and `build` if there are libraries), I can run `program_name` from console (because I have added `~/Golang/bin` in `$PATH` variable)

what is wrong?
How can I create an executable command to run in shell?

**Comment by karlseguin** [comment]
I'm not 100% sure I understand your question. `go run` doesn't "install" the binary in $GOPATH/bin. So you shouldn't be seing anything in your `$GOPATH/bin`.

go install is useful for tools you want to distribute, but i think for a normal application, you want to use go run in development, and go build to deploy. You cold do `go build -o $GOPATH/bin/shoppin main/main.go` which would put the binary where you want it.

Again, not sure if that help.

**Comment by jopacicdev** [comment]
`$GOPATH/bin` is a folder; and you build with `go build` command

**Comment by marco-m** [comment]
Looks like this can be closed :-)
