### ISSUE TITLE
Link to Traditional Chinese version

### ISSUE THREAD

**Issue by kevingo** [karlseguin/the-little-go-book#46]
Hi, I am working on the translation of the little go book on Traditional Chinese version and it almost finished.

The link goes here: [https://github.com/kevingo/the-little-go-book](https://github.com/kevingo/the-little-go-book) 

I will put the table of content on the README.md so that viewers can easily navigate the contents by visiting the repo.

Thanks for your effort writing this material, I've learned a lot from it. Although there has a Chinese version, it still contains syntax difference and I tried to updated the latest contents and examples. So I decided to make a Traditional Chinese version.

Hope it can be added to your README. 

Regards.

**Comment by karlseguin** [comment]
Thanks for this. I added a link inside the readme :)
