### ISSUE TITLE
Translate to Persian

### ISSUE THREAD

**Issue by Kiarashbakhtiar** [karlseguin/the-little-go-book#70]
Hi Karl,

I've decided to translate your book into Persian. If you wish, you can add my fork and I am planning to finish it.

[https://github.com/Kiarashbakhtiar/the-little-go-book-fa](https://github.com/Kiarashbakhtiar/the-little-go-book-fa)

Best Regards
Kiarash Bakhtiar

**Comment by karlseguin** [comment]
This is great, thanks!

Let me know when it's done and I'll update the readme :+1:
