### ISSUE TITLE
Appears to be an errant "Chapter 6" on the title page of Chapter 3

### ISSUE THREAD

**Issue by laneroberts** [karlseguin/the-little-go-book#71]
Page 40 (39 in book numbering) says "Chapter 6" just above "Chapter 3 - Maps, Arrays and Slices"

**Comment by laneroberts** [comment]
Actually, all the chapter heading pages appear to have the numerical chapter number at the top, unless it's an artifact of Evince...

**Comment by karlseguin** [comment]
I think I've fixed the issue with https://github.com/karlseguin/the-little-go-book/commit/82901f43334c7e9f824d3194f1d7445143301559  I've regenerated the pdf and updated my blog to point to the new one.

**Comment by laneroberts** [comment]
Fix looks good to me!
