### ISSUE TITLE
slices, page 44

### ISSUE THREAD

**Issue by allanychong** [karlseguin/the-little-go-book#72]
it is not at all clear that on pg 44, that when doing a subslice, 
the indexes of a subslice like scores[2:4] DO match the slice indexes, 
BUT the range included will include the first number, and exclude the second 
number (i.e., that will return scores[2], scores[3], but NOT scores[4].   

thanks,
great little book.

allan

**Comment by karlseguin** [comment]
Thanks. What do you think of:
https://github.com/karlseguin/the-little-go-book/commit/a010b28c58023238ec943620736626cdc8f29f73

**Comment by allanychong** [comment]
perfect!   i actually was so confused I wrote a couple of
programs to test behavior before submitting comment.

thanks,
allan
